### ISSUE TITLE
Resource usage information?

### ISSUE THREAD

**Issue by IngwiePhoenix** [aind-containers/aind#18]
In order to use Matrix with Whatsapp on a Linux phone - i.e. Librem 5 - I need to run WhatsApp somewhere. So, I thought about using this project, which was recommended to me by a friend who had read about it before, to run WhatsApp on my remote server, so that I could then set up my WhatsApp-Matrix-Bridge to allow me to use WhatsApp from within Riot or any other messenger I wanted to use.

But my Server is unfortunately a very tiny box with just about 8GB of memory. I might upgrade ti anyway, but it would be good to know what resource usage I can expect out of this container. Basically, how much memory does it consume in average? That's the most I'd need to know, really.

**Comment by AkihiroSuda** [comment]
On start up:
```console
$ docker stats --no-stream 
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
682569ce6d30        aind                1.54%               1.798GiB / 7.748GiB   23.20%              52.1kB / 9.88kB     234MB / 122MB       558
```

When browsing random web sites using Firefox:
```console
$ docker stats --no-stream 
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
682569ce6d30        aind                3.23%               2.111GiB / 7.748GiB   27.25%              4.42MB / 4.78MB     249MB / 125MB       654
```

**Comment by AkihiroSuda** [comment]
So 8GB of memory should be enough :)
