### ISSUE TITLE
Investigate remote connection web apps

### ISSUE THREAD

**Issue by AkihiroSuda** [aind-containers/aind#23]
Ideally we should port `anbox session-manager` to WASM (with WebGL) using Emscripten, but  for now, we should just prove the rough concept with minimum effort

### Requirements
* No client dependency other than Chrome or Firefox
* Friendly to phones and tablets
* Friendly to OIDC/LDAP/AD
* Potentially extensible to support redirection of cameras and notifications

### Existing web apps to investigate
* https://github.com/novnc/noVNC
* http://guacamole.apache.org/
* ~~https://github.com/cedrozor/myrtille~~ (Requires Windows server)
* ~~https://github.com/FreeRDP/FreeRDP-WebConnect~~ (seems inactive)

**Comment by mainmachine** [comment]
Xpra supports HTML5 and is supposedly much more efficient than VNC, but it is a beast to get working. I got it working on bare metal, but ran into an issue attempting to use it to run Anbox. I was using Ubuntu 18.04 as a base and ANbox installed via snap - might be a non-issue running xpra insied the same container as in AIND.

https://xpra.org/
https://xpra.org/trac/wiki/Clients/HTML5

**Comment by mainmachine** [comment]
Guacamole is probably not suitable. I use it for passing an RDP connection through a firewall, and it works great for that but it's not going to give the low latency you want for GUI interaction with android apps.

**Comment by jc-lab** [comment]
Xpra looks good to me.
There are several problems to be solved, but it is faster than VNC and requires no fvwm desktop.
https://github.com/jc-lab/aind/tree/xpra-display

Problems:
- Sometimes can't escape from Black Screen.
- When org.anbox.appmgr.AppViewActivity is killed, it must be restarted.

**Comment by AkihiroSuda** [comment]
implemented in https://github.com/aind-containers/aind/pull/73
