### ISSUE TITLE
Install Google Playstore

### ISSUE THREAD

**Issue by roflcoopter** [aind-containers/aind#38]
I'm trying to get Google Playstore to work so i can install Google Home app, but I'm running out of ideas.

I tried utilizing [this](https://github.com/geeks-r-us/anbox-playstore-installer/blob/master/install-playstore.sh) script and modifying it slightly but cant really wrap my head around it.
Do you understand what needs to be done to get Playstore to work?

**Comment by AkihiroSuda** [comment]
I don't think Google allow this :(

**Comment by roflcoopter** [comment]
Ahh too bad, thanks anyway
