### ISSUE TITLE
Unable to open Port 

### ISSUE THREAD

**Issue by laurentdebricon** [aind-containers/aind#44]
Hello, i have a webserver running on port 4545 in anbox.
I can't manage to contact it, even though i have set up the port redirect :( 
(if i launch firefox in anbox and access localhost:4545 my webserver is running)

```
docker run -td --name aind --privileged -p 5900:5900 -p 4545:4545 -v /lib/modules:/lib/modules:ro aind/aind
```
```
me@joujou ~ $ docker port CONTENER_ID
4545/tcp -> 0.0.0.0:4545
5900/tcp -> 0.0.0.0:5900
```
docker port forward is setup, let's verify :
```
docker exec -it CONTENER_ID bin/bash
```
```
root@665be689fda4:/# apt install net-tools
root@665be689fda4:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5559          0.0.0.0:*               LISTEN      142/anbox           
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      137/x11vnc          
tcp        0      0 127.0.0.1:5037          0.0.0.0:*               LISTEN      883/adb             
tcp6       0      0 :::5900                 :::*                    LISTEN      137/x11vnc     
```
port 4545 is not listed as open :( 
I am unable to contact the webserver running in docker anbox.

What am i missing ?
best regards

**Comment by AkihiroSuda** [comment]
This doesn't work because we nest an LXC container inside Docker.
A workaround would be to run socat + nsenter.

e.g. ` sudo socat -t -- TCP-LISTEN:4545,reuseaddr,fork EXEC:"nsenter -n -t $(pgrep YOUR_SERVER_APP) socat -t -- STDIN TCP4\:127.0.0.1\:4545"`

**Comment by laurentdebricon** [comment]
Great ! it works !
i'm glad I asked the question, it is tricky.
best regards
