### ISSUE TITLE
intermittent failure: anbox[70]: Could not create loopback device: No such file or directory

### ISSUE THREAD

**Issue by AkihiroSuda** [aind-containers/aind#5]
```console
$ docker exec -t aind systemctl status anbox-container-manager
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2020-04-09 00:45:35 UTC; 1min 22s ago
    Process: 42 ExecStartPre=/sbin/modprobe ashmem_linux (code=exited, status=0/SUCCESS)
    Process: 47 ExecStartPre=/sbin/modprobe binder_linux (code=exited, status=0/SUCCESS)
    Process: 50 ExecStartPre=/usr/bin/mkdir -p /dev/binderfs (code=exited, status=0/SUCCESS)
    Process: 51 ExecStartPre=/usr/bin/mount -t binder none /dev/binderfs (code=exited, status=0/SUCCESS)
    Process: 53 ExecStartPre=/usr/local/share/anbox/anbox-bridge.sh start (code=exited, status=0/SUCCESS)
    Process: 70 ExecStart=/usr/local/bin/anbox container-manager --daemon --data-path=/var/lib/anbox --android-image=/android.img --use-rootfs-overlay (code=exited, status=1/FAILURE)
    Process: 72 ExecStopPost=/usr/local/share/anbox/anbox-bridge.sh stop (code=exited, status=0/SUCCESS)
   Main PID: 70 (code=exited, status=1/FAILURE)

Apr 09 00:45:34 2de4fc9962f0 systemd[1]: Starting Anbox Container Manager...
Apr 09 00:45:35 2de4fc9962f0 systemd[1]: Started Anbox Container Manager.
Apr 09 00:45:35 2de4fc9962f0 anbox[70]: Could not create loopback device: No such file or directory
Apr 09 00:45:35 2de4fc9962f0 systemd[1]: anbox-container-manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 09 00:45:35 2de4fc9962f0 systemd[1]: anbox-container-manager.service: Failed with result 'exit-code'.
```

**Comment by benleb** [comment]
this just occurs on host networking right? with a bridged one everything works fine 👍

**Comment by AkihiroSuda** [comment]
Doesn't seem related to NW

**Comment by zytry** [comment]
I got the same issue on ubuntu 18.0.4 VM.

● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2020-04-11 07:11:28 UTC; 3min 17s ago
    Process: 739 ExecStartPre=/sbin/modprobe ashmem_linux (code=exited, status=0/SUCCESS)
    Process: 740 ExecStartPre=/sbin/modprobe binder_linux (code=exited, status=0/SUCCESS)
    Process: 741 ExecStartPre=/usr/local/share/anbox/anbox-bridge.sh start (code=exited, status=0/SUCCESS)
    Process: 758 ExecStart=/usr/local/bin/anbox container-manager --daemon --data-path=/var/lib/anbox --android-image=/android.img --use-rootfs-over>
    Process: 760 ExecStopPost=/usr/local/share/anbox/anbox-bridge.sh stop (code=exited, status=0/SUCCESS)
   Main PID: 758 (code=exited, status=1/FAILURE)

Apr 11 07:11:27 6169996ccb9b systemd[1]: Starting Anbox Container Manager...
Apr 11 07:11:28 6169996ccb9b systemd[1]: Started Anbox Container Manager.
Apr 11 07:11:28 6169996ccb9b anbox[758]: Could not create loopback device: No such file or directory
Apr 11 07:11:28 6169996ccb9b systemd[1]: anbox-container-manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 11 07:11:28 6169996ccb9b systemd[1]: anbox-container-manager.service: Failed with result 'exit-code'.
