### ISSUE TITLE
Startup fails when modules cannot be loaded, but loading is not necessary

### ISSUE THREAD

**Issue by funnyflowerpot** [aind-containers/aind#62]
Hi,

I'm currently trying to get `aind` working on my Gentoo laptop. While I still struggle with `anbox-bridge.sh` (different topic), I noticed that `anbox-container-manager-pre.sh` could be improved:

My system has the magic that provides `/dev/ashmem` and `/dev/binder` compiled into the kernel, not as separate modules. As those modules could not be found, the starting `aind` fails.

Running `anbox-container-manager-pre.sh` seems to not be necessary in my case. I removed the dependency in from `anbox-container-manager.service` and I got no errors anymore. The dependency could be added conditionally when placing the service-file. Another would be to add if-statements in the shell script to determine whether those device files already exist. 

This change would make `aind` more roboust and compatible with other operating systems.

**Comment by Fuseteam** [comment]
do we have a way to robust determine when the modules are compiled into the kernel? then we could use that to make anbbox-container-manger-pre.sh optional perhaps

**Comment by Fuseteam** [comment]
@funnyflowerpot can you check if ` grep binder /proc/devices` and ` grep ashmem /proc/misc` can check if the modules are compiled in?

**Comment by funnyflowerpot** [comment]
Sorry for the lack of response, the last days were a bit crazy.

I get no output for `grep binder /proc/devices`, but `grep ashmem /proc/misc` gives me:
```
 62 ashmem
```
Similarly I get the following on `grep '\<binder\>' /proc/misc`, which might be what you wanted:
```
 61 binder
```

The angular brackets denote start-of-word and end-of-word, as without them I get a few more irrelevant results.

> do we have a way to robust determine when the modules are compiled into the kernel?

After thinking about it a bit more, maybe the following could help too. In [`anbox-container-manager-pre.sh`](https://github.com/aind-containers/aind/blob/2b11ec6171dfdbf3142780d7baad139130883d5a/src/anbox-container-manager-pre.sh) we find the following code. I'll take `ashmem` as example, but I think it's similar for `binder`.
```
# ashmem
/sbin/modprobe ashmem_linux
if [ ! -e /dev/ashmem ]; then
	mknod /dev/ashmem c 10 55
fi
```
On my system `modprobe` breaks, because there is no module `ashmem_linux`. However, I do have `/dev/ashmem` available. So maybe we could rewrite it to this:
```
# ashmem

# device file available, because module already loaded or compiled into the kernel?
if [ ! -e /dev/ashmem ]; then
	# neither compiled into kernel nor loaded; load module
	/sbin/modprobe ashmem_linux
	if [ ! -e /dev/ashmem ]; then
		mknod /dev/ashmem c 10 55
	fi
fi
```
This will still break, if `ashmem_linux` is not available. However, I think this would be necessary to allow operation without using [`anbox-modules`](https://github.com/anbox/anbox-modules), since the naming of the modules in seems to be non-standard.

Sorry for not PRing it myself, I cannot test quickly these days.

**Comment by Fuseteam** [comment]
wait you get binder in /proc/misc? that's weird

so I was thinking of adding this in front of everything:
```
ashmem=`grep ashmem /proc/misc`
binder=`grep binder /proc/devices`
if [[ -n  "$ashmem" && -n "$binder" ]]; then
    echo "binder and ashmem found!"
    exit 0
fi
```
but binder seems to be the rogue one, as binder used to a device and now it is part of binderfs so on my 18.04 machines I can find binder in `/proc/devices` while on my 20.04 machines I can find it in `/proc/filesystems`
considering anbox now supports binderfs it might be an idea to update everything to binderfs tho as android 8+, when anbox finally get a newer image, does need multiple binders

**Comment by Fuseteam** [comment]
heh i managed to simplify it to: 
```
grep -q ashmem /proc/misc && grep -q binder /proc/devices && { echo "binder and ashmem found!"; exit 0; }
```
i was trying to include binderfs as well but that also needs [this](https://github.com/aind-containers/aind/blob/82ea70fa5b295c3b6be44068230e84b91121a5b6/src/anbox-container-manager-pre.sh#L17-L20) to be executed

**Comment by Fuseteam** [comment]
i ended up doing it like https://github.com/Fuseteam/aind/commit/156012a5f541029d023fc5d78d78eac86dacd808 can you check if that works for you?

**Comment by funnyflowerpot** [comment]
Yes, that works for me! Looks great, thank you for taking your time!

I also find it a bit strange that `binder` is not in `/proc/filesystems`. I checked my kernel config again and "binderfs" seemed to be missing. (Apparently it didn't hurt that much so far?) I will check again after the next reboot!

**Comment by Fuseteam** [comment]
yeah binder and binderfs are separate modules, binder was first, binderfs arose from the need to have multiple binder devices. what i find weird is that binder is missing in `/proc/devices`

**Comment by funnyflowerpot** [comment]
After building `binderfs` into the kernel, I get the following results.
```
$ grep binder /proc/filesystems
nodev	binder
$ grep binder /proc/devices 
248 binder
$ grep binder /proc/misc 
$
```
That is, no results on the last command this time. I double-checked and this is different from the last time I had my machine booted. Maybe `/proc/misc` is something like a fallback file to list `binder` availability, when it is not available as `binderfs`. But still, that sounds weird indeed.

Aside, I think the issue is pretty much resolved. I opt for closing, but please let me know, if more debugging can be done! :)

**Comment by Fuseteam** [comment]
i think it is resolved, tho now i kinda wonder if the check in `/proc/misc` is needed or not

**Comment by funnyflowerpot** [comment]
Looking into `drivers/android/binder.c` of the kernel source code, I find the installation of a "misc device". It seems that for me this was enough and `binderfs` seems to not be a strict requirement in terms of function. Hence looking into `/proc/filesystems` might be checking for the wrong thing?

However, I cannot find setup of a "misc device" in `anbox-modules`'s [`binder.c`](https://github.com/anbox/anbox-modules/blob/master/binder/binder.c). Not sure where that code is taken from or how heavily it was modified.

**Comment by Fuseteam** [comment]
Yeah that might be it, binderfs is not strict requirement now but it is what is required for multiple binder such as what is needed for android 8+
