### ISSUE TITLE
using dwm instead of fvwm

### ISSUE THREAD

**Issue by Fuseteam** [aind-containers/aind#71]
is there any particular reason why fvwm was chosen?
some of the benefits I can see with dwm is that due to its small code base we could configure it to show all apps in "fullscreen" hide the top bar and other such optimizations.
in my quick test(no modifications) one issue I have seen is that the application that gets started is initially black, moving it around seems to fix it

**Comment by Fuseteam** [comment]
i have a working docker image with stock dwm under `fuseteam/aindwm` fwiw

**Comment by AkihiroSuda** [comment]
I chose fvwm because I wanted title bars.
Other candidates could be ctwm, icewm, and blackbox.

**Comment by Fuseteam** [comment]
ah alright, tho now we technically have 2 titlebars
